title: Kinjal Singh
logo: https://lh3.googleusercontent.com/a/ACg8ocKx9RdA4DB3jOxxBl89EQU8UF7MPepg6C5G22wHlwlFThtBHrs=s576-c-no
#description: text below image
#show_downloads: false
theme: jekyll-theme-minimal
